### ISSUE TITLE
Gesture image of the online demo

### ISSUE THREAD

**Issue by czqInNanjing** [mit-han-lab/temporal-shift-module#142]
Hi, I have succeeded to deploy the online demo on my tx2.
But I found some gestures not easy to recognized. I am not sure whether it is because my gesture is wrong. 

I wonder what dataset is used to train the model used in the  demo? I wonder if you could provide some images（sign） of the gesture. Thank you very much!

**Comment by Nauman007** [comment]
you can try the gestures they used in their online demo for cross check...

**Comment by czqInNanjing** [comment]
the dataset is from here: https://20bn.com/datasets/jester/v1

**Comment by NB-Xie** [comment]
> the dataset is from here: https://20bn.com/datasets/jester/v1

hello there! may i know:

did you use the Jester dataset ,
and did you change the bi-direction to uni-direction shift in training?
appreciate!

**Comment by Nauman007** [comment]
hi, I used  the TSN models they provided in the models, specifically I used MobileNet variant as I wanted a low cost model.
secondly I did change bi-direction to uni-direction shift while training.

**Comment by NB-Xie** [comment]
> hi, I used the TSN models they provided in the models, specifically I used MobileNet variant as I wanted a low cost model.
> secondly I did change bi-direction to uni-direction shift while training.
Hi, really appreciate your answer! 
And may I know:
1. did you use the  "mobilenet_v2_tsm.py(which includes the buffer)" they provided in demo in the **online test**?  
2. if you use the bi-direction in training but uni-direction in testing, will the result be heavily affected?

I tried the TSN in training (while I didn't change bi-direction)(num_seg = 8),  and loaded the trained state_dict into mobilenet_v2 in mobilenet_v2_tsm.py, and then modified and applied the  "main.py " in /online_demo .

it turned out that almost all gestures were classified as "no gesture" or "doing other things" 

@Nauman007 @czqInNanjing   thank you

**Comment by NB-Xie** [comment]
and they met the similar issue:
#39 (comment)

**Comment by Nauman007** [comment]
Hi,
1- No I didn't use the .py file u mentioned, instead I made my own for online demo as I didn't have experience working with onnx or tvm.
2- I had tested the same scenario u mentioned, in my case results were not  heavily affected. But it did improve results when I trained the model with Uni-direction instead of bi-direction.

**Comment by NB-Xie** [comment]
> Hi,
> 1- No I didn't use the .py file u mentioned, instead I made my own for online demo as I didn't have experience working with onnx or tvm.
> 2- I had tested the same scenario u mentioned, in my case results were not heavily affected. But it did improve results when I trained the model with Uni-direction instead of bi-direction.

Thank you for replying me!
And how did you set your online demo? I'm curious that is the input size set to (1, 3, 224, 224) as frame by frame (which is done in their online_demo), or set to (num_seg, 3, 224, 224) as did in the traing phase (e.g. num_seg =8)?

**Comment by andrewwang0612** [comment]
> hello there! we are working on the same issue, may I know:

Sorry to bother you!!
Did you already know the reason of the input size set to (1, 3, 224, 224) as frame by frame (which is done in their online_demo), or set to (num_seg, 3, 224, 224) as did in the traing phase (e.g. num_seg =8)?

appreciate!!
