### ISSUE TITLE
how to test ?

### ISSUE THREAD

**Issue by ucasiggcas** [mit-han-lab/temporal-shift-module#42]
hi,dear
Do not want test on the txt file's images
Just want to test other images or videos ,so how to ?
pls supply the file
### kinetics/labels/val_videofolder.txt
or tell me what's on it ?

thx

**Comment by ucasiggcas** [comment]
and what's the meaning of the 1,3,5,10, any difference ??
```
if args.test_crops == 1:
    cropping = torchvision.transforms.Compose([
            GroupScale(net.scale_size),#256
            GroupCenterCrop(input_size),#224
        ])
elif args.test_crops == 3:  # do not flip, so only 5 crops
    cropping = torchvision.transforms.Compose([
            GroupFullResSample(input_size, net.scale_size, flip=False)
        ])
elif args.test_crops == 5:  # do not flip, so only 5 crops
    cropping = torchvision.transforms.Compose([
            GroupOverSample(input_size, net.scale_size, flip=False)
        ])
elif args.test_crops == 10:
    cropping = torchvision.transforms.Compose([
            GroupOverSample(input_size, net.scale_size)
        ])
```

**Comment by ucasiggcas** [comment]
any one could supply the kinetics400 dataset ??
if could use ### wget will be great great !!!

**Comment by tonylins** [comment]
Hi, sorry that the `test_models.py` is complicated. I was trying to enable the ensemble test in the script. I will try to make it simple in the next update. 

For the current codebase, the videos are firstly decoded into images (you may look into the TSN code base for the details (https://github.com/yjxiong/temporal-segment-networks)). So to test on your own video, you may first decode the video using ffmpeg.

For the file `kinetics/labels/val_videofolder.txt`, I provide a script `tools/gen_label_kinetics.py` to generate the label. Since Kinetics dataset is usually not complete (some videos are unable to download), I don't think it is a good idea to provide a fixed file. You can easily generate the list file using the script.

For the test crops, 1-crop is just the center crop. 3-crop is the way used in Non-local network. 5 and 10-crop are used in the TSN paper.

**Comment by fairleehu** [comment]
hello, do you get the dataset?
